services:
  focusflow-api:
    pull_policy: if_not_present
    build:
      context: .
      dockerfile: src/FocusFlow.WebApi/Dockerfile
    ports:
      - "8080:8080" # HTTP only - internal service - API doesn't need HTTPS in dev because communicates inside Docker network.
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings:DefaultConnection=Host=postgres-db;Port=5432;Database=FocusFlowDb;Username=postgres;Password=postgres"
      - "JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm"
      - "JwtSettings__Issuer=FocusFlowApi"
      - "JwtSettings__Audience=FocusFlowClient"
      - TEST_USER_EMAIL=test@example.com
      - TEST_USER_PASSWORD=Password123!
    depends_on:
      postgres-db:
        condition: service_healthy
    tmpfs:
      - /tmp
      # no certificate mount for API in dev

  focusflow-blazor:
    pull_policy: if_not_present
    build:
      context: .
      dockerfile: src/FocusFlow.BlazorApp/Dockerfile
    ports:
      - "5050:8080" # HTTP
      - "5051:8081" # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ApiBaseUrl=http://focusflow-api:8080
      - "JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm"
      - "JwtSettings__Issuer=FocusFlowApi"
      - "JwtSettings__Audience=FocusFlowClient"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD:-MyPfxPassword123!}
    depends_on:
      - focusflow-api
    tmpfs:
      - /tmp
    volumes:
      - ./certs:/https:ro # Mount development certificate
      - ./dataprotection:/dataprotection-keys:rw # Persist keys across restarts

  postgres-db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: FocusFlowDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports removed for production/security
    volumes:
      - focusflow-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # focusflow-seq:
  #   image: datalust/seq:2024.3
  #   ports:
  #     - "5342:5341"
  #     - "8082:80"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1g
  #       reservations:
  #         memory: 512m
  #   volumes:
  #     - seq-data:/data

volumes:
  focusflow-db-data:
  # seq-data:
