<Project Sdk="Microsoft.NET.Sdk.Web">
 
  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" />
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Fluxor" />
    <PackageReference Include="Fluxor.Blazor.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Sinks.BrowserConsole" />    
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FocusFlow.Application\FocusFlow.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FocusFlow.Domain.Enums" />
  </ItemGroup>

  <!-- Add this to ensure static assets are copied -->
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

</Project>
