apiVersion: v1
kind: ConfigMap
metadata:
  name: focusflow-config
  namespace: focusflow
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  POSTGRES_HOST: "10.100.178.155"
  POSTGRES_DB: "focusflow"
  POSTGRES_USER: "focusflow"
