apiVersion: v1
kind: ConfigMap
metadata:
  name: focusflow-config
  namespace: focusflow
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  POSTGRES_HOST: "focusflow-postgres"
  POSTGRES_DB: "focusflow"
  POSTGRES_USER: "focusflow"
