apiVersion: v1
kind: Secret
metadata:
  name: focusflow-secrets
  namespace: focusflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: "demo123"
  JWT_SECRET: "demo-jwt-secret-key-minimum-32-chars-long"
