<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FocusFlow.Domain\FocusFlow.Domain.csproj" />
    <ProjectReference Include="..\FocusFlow.Application\FocusFlow.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />    
  </ItemGroup>
</Project>
