# Use the official ASP.NET Core SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the .csproj files and restore dependencies
COPY FocusFlow.sln .
COPY src/FocusFlow.WebApi/*.csproj src/FocusFlow.WebApi/
COPY src/FocusFlow.Application/*.csproj src/FocusFlow.Application/
COPY src/FocusFlow.Domain/*.csproj src/FocusFlow.Domain/
COPY src/FocusFlow.Infrastructure/*.csproj src/FocusFlow.Infrastructure/
RUN dotnet restore FocusFlow.sln

# Copy the rest of the application code
COPY src/FocusFlow.WebApi/ src/FocusFlow.WebApi/
COPY src/FocusFlow.Application/ src/FocusFlow.Application/
COPY src/FocusFlow.Domain/ src/FocusFlow.Domain/
COPY src/FocusFlow.Infrastructure/ src/FocusFlow.Infrastructure/

# Build the application
WORKDIR /app/src/FocusFlow.WebApi
RUN dotnet build "FocusFlow.WebApi.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "FocusFlow.WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Use the official ASP.NET Core runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FocusFlow.WebApi.dll"]
